Tạo các tensor đơn giản

In [ ]:
import torch

#tạo tensor 1 chiều với 3 phần tử là 1
ts = torch.ones(3)

#tạo tensor từ một list
points = torch.tensor([1.0,2.0,3.0,4.0,5.0])

#check chiều của một tensor
points_shape = points.shape

#tạo tensor với nhiều chiều
mul_ts = torch.ones(2,3) #2 mảng 1 chiều, mỗi mảng 1 chiều chứa 3 phần tử 

_3ds = torch.tensor([[1.0,4.0],[2.0,2.0],[3.0,5.0]])

_3ds_shape = _3ds.shape
print(_3ds[2,0])
print(_3ds_shape)
print(mul_ts)
print(points_shape)
print(points)
print(ts)

Storage trong tensor

In [19]:
points = torch.tensor([[1.0,2.0],[5.0,6.0]])

#storage() : là một array gồm các giá trị trong một tensor, luôn chỉ là array
poinst_storage = points.storage()

#truy cập vào từng phẩn tử trong storage
index_poinst_storage = poinst_storage[0]

print(index_poinst_storage)
print(ts.storage())

1.0
 1.0
 2.0
 5.0
 6.0
[torch.FloatStorage of size 4]


Size, storage offset và strides

In [32]:
dt = torch.tensor([[1.0,3.0],[5.0,6.0],[8.0,6.0]])
dt_storage = dt.storage()

#size(shape) : là một tuple, chỉ kích thước của tensor. Ví dụ : (3,3) : có 3 hàng, 3 cột
print(dt.shape)

#storage offset : vị trí trong storage của phần tử đầu tiên trong tensor
storage_dt = dt[1]
print(storage_dt.storage_offset())

#strides : số phần tử sẽ được bỏ qua để storage nhảy đến phần tử tiếp theo 
print(storage_dt.stride())

#thay đổi subtensor làm thay đổi luôn tensor gốc
storage_dt[0] = 10.0
print(dt)

#clone subtensor ra một tensor mới hoàn toàn
storage_dt2 = dt[2].clone()
storage_dt2[0] = 12.0
print(dt)



torch.Size([3, 2])
2
(1,)
tensor([[ 1.,  3.],
        [10.,  6.],
        [ 8.,  6.]])
tensor([[ 1.,  3.],
        [10.,  6.],
        [ 8.,  6.]])


Chuyển vị (transpose)

In [37]:
point_t = torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])

#chuyển vị (transpose)
sencond_point = point_t.t()

print(point_t)
print(sencond_point)
print(point_t.storage())
print(sencond_point.storage())
print(point_t.stride())
print(sencond_point.stride())
print(point_t.shape)
print(sencond_point.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.FloatStorage of size 6]
 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.FloatStorage of size 6]
(2, 1)
(1, 2)
torch.Size([3, 2])
torch.Size([2, 3])


Các kiểu dữ liệu trong tensor

In [46]:
#các kiểu dữ liệu : float32, float64, float16, int8, uint8, int16, int32, int64

data = torch.zeros(6)

#kiểm tra kiểu dữ liệu của tensor
type_of_data = data.dtype

#định dạng kiểu dữ liệu lúc tạo tensor
data2 = torch.tensor([[1.0,2.0],[3.0,4.0]],dtype=torch.int16)

#ép kiểu dữ liệu
data3 = data2.to(torch.float64)

print(type_of_data)
print(data2.dtype)
print(data3.dtype)

torch.float32
torch.int16
torch.float64


Chuyển sang kiểu numpy

In [48]:
point_torch = torch.ones(6)

#chuyển sang kiểu numpy
point_numpy = point_torch.numpy()
print(type(point_numpy))

<class 'numpy.ndarray'>


Lưu và load tensor

In [50]:
#lưu tensor vào file torch_save.t
torch.save(point_torch,"torch_save.t")

#load tensor từ file torc_save.t
load_torch = torch.load("torch_save.t")
print(load_torch)


tensor([1., 1., 1., 1., 1., 1.])


Lưu và load file dưới dạng hdf5 file

In [51]:
%pip install h5py

In [52]:
import h5py

#lưu dưới dạng hdf5
h5_py = h5py.File("point.hdf5","w")
ds = h5_py.create_dataset('coords',data=point_torch.numpy()) #coords : khóa để truy cập vào file hdf5


In [60]:
#load tensor từ file
h5_py = h5py.File("point.hdf5","r")
data = h5_py['coords']
point = data[1:]
dset = torch.from_numpy(point)
print(dset)

tensor([1., 1., 1., 1., 1.])


Chuyển sang xử lý bằng GPU

In [58]:
#chuyển về xử lý bằng gpu
point_to_change = torch.tensor([[2.0,2.0],[3.0,4.0]],device="cuda")
point_change = point_torch.to(device="cuda")

#chuyển về xử lý với CPU
point_cpu = point_to_change.to(device="cpu")

AssertionError: Torch not compiled with CUDA enabled