Load file csv

In [12]:
#Chuyển từ dạng bảng thành numpy array
import numpy as np

wineq_numpy = np.loadtxt("winequality-white.csv",dtype=np.float32, delimiter = ",",skiprows=1)
print(wineq_numpy[:5])
print(wineq_numpy.shape)

[[7.000e+00 2.700e-01 3.600e-01 2.070e+01 4.500e-02 4.500e+01 1.700e+02
  1.001e+00 3.000e+00 4.500e-01 8.800e+00 6.000e+00]
 [6.300e+00 3.000e-01 3.400e-01 1.600e+00 4.900e-02 1.400e+01 1.320e+02
  9.940e-01 3.300e+00 4.900e-01 9.500e+00 6.000e+00]
 [8.100e+00 2.800e-01 4.000e-01 6.900e+00 5.000e-02 3.000e+01 9.700e+01
  9.951e-01 3.260e+00 4.400e-01 1.010e+01 6.000e+00]
 [7.200e+00 2.300e-01 3.200e-01 8.500e+00 5.800e-02 4.700e+01 1.860e+02
  9.956e-01 3.190e+00 4.000e-01 9.900e+00 6.000e+00]
 [7.200e+00 2.300e-01 3.200e-01 8.500e+00 5.800e-02 4.700e+01 1.860e+02
  9.956e-01 3.190e+00 4.000e-01 9.900e+00 6.000e+00]]
(4898, 12)


In [20]:
#Chuyển numpy array sang tensor
import torch

wineq = torch.from_numpy(wineq_numpy)
print(wineq)

tensor([[ 7.0000,  0.2700,  0.3600,  ...,  0.4500,  8.8000,  6.0000],
        [ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
        [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
        ...,
        [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
        [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
        [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]])


Tách data ra làm 2 loại : data để huấn luyện và nhãn

In [51]:
#tách để tạo data huấn luyện
train_winequality = wineq[:, :-1]
print(train_winequality.shape)

torch.Size([4898, 11])


In [40]:
#tách để tạo cột nhãn
label_winequality = wineq[:,-1]
label_winequality = label_winequality.to(torch.int64)
print(label_winequality[:5])

tensor([6, 6, 6, 6, 6])


In [49]:
#chuyển cột nhãn thành vecto one hot
label_onehot = torch.zeros(len(label_winequality),10)
print(label_winequality.shape[0])
label_onehot.scatter_(1, label_winequality.unsqueeze(1),1.0) #với mỗi hàng trong cột nhãn, lấy ra giá trị của nó, từ đó thay giá trị 1 vào vị trí tương ứng với với giá trị trong vecto onehot
print(label_onehot[:3])

#chuyển lại thành cột nhãn
label_unsqueezed = label_winequality.unsqueeze(1)
print(label_unsqueezed)

4898
tensor([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])
tensor([[6],
        [6],
        [6],
        ...,
        [6],
        [7],
        [6]])


In [57]:
#tính giá trị trung bình trên từng cột
train_winequality_mean = torch.mean(train_winequality,dim=0)
print(train_winequality_mean)

#tính độ lệnh chuẩn trên từng cột
train_winequality_var = torch.var(train_winequality,dim=0)
print(train_winequality_var)

#chuẩn hóa dữ liệu
train_winequality_normalized = (train_winequality - train_winequality_mean)/ train_winequality_var
print(train_winequality_normalized) 

tensor([-8.7229e-07,  2.0561e-06,  2.5172e-06,  8.3724e-09, -1.3022e-05,
        -5.0137e-09,  4.3809e-10, -1.5950e-05,  5.4386e-06,  3.8007e-06,
         4.4004e-08])
tensor([1.4043e+00, 9.8430e+01, 6.8279e+01, 3.8872e-02, 2.0950e+03, 3.4573e-03,
        5.5368e-04, 1.1179e+05, 4.3857e+01, 7.6777e+01, 6.6032e-01])
tensor([[ 1.4521e-01, -8.2411e-03,  2.5809e-02,  ..., -1.8827e-01,
         -3.9847e-02, -1.7143e+00],
        [-5.5479e-01,  2.1759e-02,  5.8085e-03,  ...,  1.1173e-01,
          1.5313e-04, -1.0143e+00],
        [ 1.2452e+00,  1.7589e-03,  6.5809e-02,  ...,  7.1733e-02,
         -4.9847e-02, -4.1427e-01],
        ...,
        [-3.5479e-01, -3.8241e-02, -1.4419e-01,  ..., -1.9827e-01,
         -2.9847e-02, -1.1143e+00],
        [-1.3548e+00,  1.1759e-02, -3.4191e-02,  ...,  1.5173e-01,
         -1.0985e-01,  2.2857e+00],
        [-8.5479e-01, -6.8241e-02,  4.5808e-02,  ...,  7.1733e-02,
         -1.6985e-01,  1.2857e+00]])
